# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uj1qq9PpMXIWTY88PrAInmueScnCdeAf
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.api import ExponentialSmoothing
from statsmodels.tsa.statespace.varmax import VARMAX
import pickle

train_url = "https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_train.csv"
train_data = pd.read_csv(train_url)
if 'Timestamp' in train_data.columns:
    train_data.rename(columns={'Timestamp': 'timestamp'}, inplace=True)
train_data['timestamp'] = pd.to_datetime(train_data['timestamp'])
train_data.set_index('timestamp', inplace=True)
train_data = train_data.asfreq('h')

y_train = train_data['trips']

model = ExponentialSmoothing(y_train, seasonal='add', seasonal_periods=24)
modelFit = model.fit()

with open("model.pkl", "wb") as f:
    pickle.dump(modelFit, f)

test_url = "https://github.com/dustywhite7/econ8310-assignment1/raw/main/assignment_data_test.csv"
test_data = pd.read_csv(test_url)
if 'Timestamp' in test_data.columns:
    test_data.rename(columns={'Timestamp': 'timestamp'}, inplace=True)

test_data['timestamp'] = pd.to_datetime(test_data['timestamp'])
test_data.set_index('timestamp', inplace=True)
test_data = test_data.asfreq('h')
pred = modelFit.forecast(steps=744)

pred.to_csv("predictions.csv")

print("Model training and prediction completed successfully!")

import matplotlib.pyplot as plt

pred = pd.read_csv("predictions.csv", index_col=0)
pred.index = pd.to_datetime(pred.index)